packaging_format = 1

[main]
id = "beszel"
name = "Beszel"
description.en = "Lightweight server monitoring hub with historical data, docker stats, and alerts."
description.fr = "Plateforme de surveillance de serveur légère avec données historiques, statistiques Docker et alertes."
version = "0.17.0~ynh1"
maintainer = "CyberByteCraft"
license = "MIT"
url = "https://github.com/henrygd/beszel"
multi_instance = false

[resources]
[resources.sources]
[resources.sources.main]
url = "https://github.com/henrygd/beszel/releases/download/v0.17.0/hub_linux_amd64.tar.gz"
dest_dir = "/opt/beszel"

[install]
size = 100
yunohost_min_version = "11.1.0"

[requirements]
yunohost = ">= 11.1.0"

[arguments]
domain = { type = "domain" }
path = { type = "path", default = "/beszel" }
admin = { type = "user", default = "admin" }
is_public = { type = "boolean", default = false }

